name: Java maven docker
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
    push: 
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/Checkout@v4
            -   name: JDK 8 version
                uses: actions/setup-java@v1
                with:
                    java-version: 1.8
            

            

    