name: python-build-test

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
jobs:
    pypy:
        runs-on: ubuntu-latest

        steps:
        -   uses: actions/checkout@v4
        -   uses: actions/setup-python@v5
            with:
                python-version: 'pypy3.9' 
        -   run: python my_script.py