name: python-build-pypy

on:
  push:
    paths:
      - "python-actions/**"
      - ".github/workflows/python-pypi.yml"
jobs:
  pypy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "pypy3.9"
      - run: python manage.py
